---
- name: Install packages - dnf
  dnf:
    name: "{{ package_list }}"
    state: present
  with_items: "{{ package_list }}"
  when: ansible_pkg_mgr == "dnf"

- name: Install packages - yum
  yum:
    name: "{{ package_list }}"
    state: present
  with_items: "{{ package_list }}"
  when: ansible_pkg_mgr == "yum"
