---
- name: Ensure ntp service is running.
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution_major_version == "6"

- name: Ensure chrony service is running.
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution_major_version == "7" 

