---
# This task list adds Google DNS to /etc/resolv.conf
- name: Add Google DNS to /etc/resolv.conf
  become: true
  blockinfile:
    dest: /etc/resolv.conf
    insertafter: "search gshome.lan"
    block: "nameserver 8.8.8.8"
