- hosts: all
  become_method: sudo
  become: true

  tasks:
    - name: Install libselinux-python
      yum: name=libselinux-python state=present

    - include: ./google_dns.yml

    - name: Ensure Chrony is installed.
      yum: name=chrony state=present

    - name: Ensure chrony service is running.
      service: name=chronyd state=started enabled=yes

    - include: ./bashrc.yml
